/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#b8c4ff",
        "outline-variant": "#c4c5d5",
        "tertiary": "#611e00",
        "error": "#ba1a1a",
        "tertiary-container": "#872d00",
        "inverse-surface": "#2f3037",
        "inverse-primary": "#b8c4ff",
        "surface-dim": "#dad9e3",
        "surface-variant": "#e3e1eb",
        "on-surface-variant": "#444653",
        "primary-container": "#1e40af",
        "error-container": "#ffdad6",
        "surface-tint": "#3755c3",
        "primary": "#00288e",
        "surface-bright": "#fbf8ff",
        "on-surface": "#1a1b22",
        "surface-container-low": "#f4f2fc",
        "surface-container-high": "#e8e7f1",
        "on-primary-fixed": "#001453",
        "on-primary-fixed-variant": "#173bab",
        "outline": "#757684",
        "on-secondary-fixed": "#0b1c30",
        "tertiary-fixed": "#ffdbce",
        "on-background": "#1a1b22",
        "on-primary": "#ffffff",
        "surface": "#fbf8ff",
        "secondary-fixed-dim": "#b7c8e1",
        "secondary": "#505f76",
        "secondary-container": "#d0e1fb",
        "on-secondary-container": "#54647a",
        "on-secondary": "#ffffff",
        "on-secondary-fixed-variant": "#38485d",
        "surface-container-highest": "#e3e1eb",
        "secondary-fixed": "#d3e4fe",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#380d00",
        "tertiary-fixed-dim": "#ffb59a",
        "primary-fixed": "#dde1ff",
        "on-error-container": "#93000a",
        "surface-container": "#eeedf7",
        "background": "#fbf8ff",
        "on-tertiary-fixed-variant": "#802a00",
        "on-tertiary-container": "#ffa583",
        "on-primary-container": "#a8b8ff",
        "on-error": "#ffffff",
        "inverse-on-surface": "#f1f0fa",
        "surface-container-lowest": "#ffffff"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "xl": "32px",
        "sm": "8px",
        "xs": "4px",
        "lg": "24px",
        "base": "8px",
        "margin": "32px",
        "2xl": "48px",
        "gutter": "24px",
        "md": "16px"
      },
      fontFamily: {
        "sans": ["Inter", "sans-serif"],
        "label-sm": ["Inter"],
        "code": ["monospace"],
        "h2": ["Inter"],
        "body-sm": ["Inter"],
        "h1": ["Inter"],
        "body-md": ["Inter"],
        "body-lg": ["Inter"],
        "label-md": ["Inter"],
        "h3": ["Inter"]
      },
      fontSize: {
        "label-sm": ["12px", { "lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "code": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "h2": ["30px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.45", "fontWeight": "400" }],
        "h1": ["36px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.55", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "1", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "h3": ["24px", { "lineHeight": "1.3", "letterSpacing": "-0.01em", "fontWeight": "600" }]
      },
      boxShadow: {
        'level-1': '0 2px 4px 0 rgba(0, 0, 0, 0.04)',
        'level-2': '0 4px 12px 0 rgba(0, 0, 0, 0.08)',
      }
    }
  },
  plugins: [],
}
